In [3]:
import pandas as pd

In [4]:
df2 = pd.read_csv('users/tengkaiyao/Desktop/Group Project Data-SFD Data-Toronto Police.csv')

In [5]:
df2

,X,Y,OBJECTID,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,...,OCC_TIME_RANGE,DIVISION,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
0,-79.234955,43.781528,1,GO-2004397105,2004/05/15 04:00:00+00,2004,May,Saturday,136,15,...,Night,D41,0,0,142,Woburn North,137,Woburn (137),-79.234955,43.781528
1,-79.618218,43.733547,2,GO-2004600109,2004/07/26 04:00:00+00,2004,July,Monday,208,26,...,Evening,D23,0,0,1,West Humber-Clairville,1,West Humber-Clairville (1),-79.618218,43.733547
2,-79.518759,43.769157,3,GO-2004311851,2004/05/14 04:00:00+00,2004,May,Friday,135,14,...,Afternoon,D31,1,1,24,Black Creek,24,Black Creek (24),-79.518759,43.769157
3,-79.378870,43.660665,4,GO-2004736004,2004/12/19 05:00:00+00,2004,December,Sunday,354,19,...,Night,D51,1,0,168,Downtown Yonge East,75,Church-Yonge Corridor (75),-79.378870,43.660665
4,-79.212435,43.812075,5,GO-2004303455,2004/04/12 04:00:00+00,2004,April,Monday,103,12,...,Evening,D42,0,0,146,Malvern East,132,Malvern (132),-79.212435,43.812075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5702,-79.362941,43.771764,5703,GO-20221038418,2022/06/02 04:00:00+00,2022,June,Thursday,153,2,...,Night,D33,0,1,53,Henry Farm,53,Henry Farm (53),-79.362941,43.771764
5703,-79.402702,43.643920,5704,GO-20221362949,2022/07/17 04:00:00+00,2022,July,Sunday,198,17,...,Night,D14,1,1,164,Wellington Place,77,Waterfront Communities-The Island (77),-79.402702,43.643920
5704,-79.196217,43.786621,5705,GO-2022336423,2022/02/21 05:00:00+00,2022,February,Monday,52,21,...,Night,D43,0,0,135,Morningside,135,Morningside (135),-79.196217,43.786621
5705,-79.443993,43.658083,5706,GO-20221765442,2022/09/11 04:00:00+00,2022,September,Sunday,254,11,...,Night,D11,0,2,83,Dufferin Grove,83,Dufferin Grove (83),-79.443993,43.658083
5706,-79.369456,43.654519,5707,GO-2022783839,2022/04/27 04:00:00+00,2022,April,Wednesday,117,27,...,Afternoon,D51,0,0,73,Moss Park,73,Moss Park (73),-79.369456,43.654519

In [6]:
df2=df2.drop(df2[df2['NEIGHBOURHOOD_158']=='NSA'].index)
df2=df2.drop(df2[df2['X']==0].index)
df2=df2.drop(df2[df2['Y']==0].index)

In [7]:
df2.head(50)

,X,Y,OBJECTID,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,...,OCC_TIME_RANGE,DIVISION,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
0,-79.234955,43.781528,1,GO-2004397105,2004/05/15 04:00:00+00,2004,May,Saturday,136,15,...,Night,D41,0,0,142,Woburn North,137,Woburn (137),-79.234955,43.781528
1,-79.618218,43.733547,2,GO-2004600109,2004/07/26 04:00:00+00,2004,July,Monday,208,26,...,Evening,D23,0,0,1,West Humber-Clairville,1,West Humber-Clairville (1),-79.618218,43.733547
2,-79.518759,43.769157,3,GO-2004311851,2004/05/14 04:00:00+00,2004,May,Friday,135,14,...,Afternoon,D31,1,1,24,Black Creek,24,Black Creek (24),-79.518759,43.769157
3,-79.378870,43.660665,4,GO-2004736004,2004/12/19 05:00:00+00,2004,December,Sunday,354,19,...,Night,D51,1,0,168,Downtown Yonge East,75,Church-Yonge Corridor (75),-79.378870,43.660665
4,-79.212435,43.812075,5,GO-2004303455,2004/04/12 04:00:00+00,2004,April,Monday,103,12,...,Evening,D42,0,0,146,Malvern East,132,Malvern (132),-79.212435,43.812075
5,-79.318704,43.759919,6,GO-2004213938,2004/03/14 05:00:00+00,2004,March,Sunday,74,14,...,Night,D33,0,0,150,Fenside-Parkwoods,45,Parkwoods-Donalda (45),-79.318704,43.759919
6,-79.197132,43.796763,7,GO-2004149554,2004/01/19 05:00:00+00,2004,January,Monday,19,19,...,Evening,D42,0,0,144,Morningside Heights,131,Rouge (131),-79.197132,43.796763
7,-79.588530,43.738688,8,GO-2004646393,2004/09/08 04:00:00+00,2004,September,Wednesday,252,8,...,Afternoon,D23,0,0,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.588530,43.738688
8,-79.427371,43.638954,9,GO-2004764704,2004/04/14 04:00:00+00,2004,April,Wednesday,105,14,...,Evening,D14,0,0,85,South Parkdale,85,South Parkdale (85),-79.427371,43.638954
10,-79.335299,43.762583,11,GO-2004619258,2004/10/27 04:00:00+00,2004,October,Wednesday,301,27,...,Evening,D33,0,1,150,Fenside-Parkwoods,45,Parkwoods-Donalda (45),-79.335299,43.762583
11,-79.589903,43.738802,12,GO-2004696934,2004/11/15 05:00:00+00,2004,November,Monday,320,15,...,Afternoon,D23,0,1,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.589903,43.738802
12,-79.507875,43.696405,13,GO-2004695551,2004/10/31 04:00:00+00,2004,October,Sunday,305,31,...,Night,D12,0,0,113,Weston,113,Weston (113),-79.507875,43.696405
13,-79.256513,43.730741,14,GO-2004811677,2004/12/19 05:00:00+00,2004,December,Sunday,354,19,...,Afternoon,D41,1,0,124,Kennedy Park,124,Kennedy Park (124),-79.256513,43.730741
14,-79.487170,43.672704,15,GO-2004641880,2004/08/27 04:00:00+00,2004,August,Friday,240,27,...,Night,D12,0,0,111,Rockcliffe-Smythe,111,Rockcliffe-Smythe (111),-79.487170,43.672704
15,-79.362998,43.660081,16,GO-2004374867,2004/05/21 04:00:00+00,2004,May,Friday,142,21,...,Evening,D51,1,0,72,Regent Park,72,Regent Park (72),-79.362998,43.660081
16,-79.272626,43.765462,17,GO-2004187244,2004/02/12 05:00:00+00,2004,February,Thursday,43,12,...,Night,D41,0,0,126,Dorset Park,126,Dorset Park (126),-79.272626,43.765462
17,-79.193292,43.763203,18,GO-2004339280,2004/04/23 04:00:00+00,2004,April,Friday,114,23,...,Evening,D42,0,0,136,West Hill,136,West Hill (136),-79.193292,43.763203
18,-79.585613,43.751010,19,GO-2004715205,2004/11/16 05:00:00+00,2004,November,Tuesday,321,16,...,Night,D23,0,1,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.585613,43.751010
19,-79.527129,43.704308,20,GO-2004597291,2004/08/28 04:00:00+00,2004,August,Saturday,241,28,...,Night,D31,0,0,113,Weston,113,Weston (113),-79.527129,43.704308
20,-79.373917,43.653962,21,GO-2004649788,2004/09/11 04:00:00+00,2004,September,Saturday,255,11,...,Afternoon,D51,0,0,168,Downtown Yonge East,75,Church-Yonge Corridor (75),-79.373917,43.653962
21,-79.553876,43.718054,22,GO-2004224089,2004/03/07 05:00:00+00,2004,March,Sunday,67,7,...,Night,D23,0,1,5,Elms-Old Rexdale,5,Elms-Old Rexdale (5),-79.553876,43.718054
23,-79.299345,43.783589,24,GO-2004491397,2004/11/10 05:00:00+00,2004,November,Wednesday,315,10,...,Afternoon,D42,0,2,118,Tam O'Shanter-Sullivan,118,Tam O'Shanter-Sullivan (118),-79.299345,43.783589
24,-79.224706,43.757835,25,GO-2004251775,2004/03/29 05:00:00+00,2004,March,Monday,89,29,...,Morning,D42,0,0,141,Golfdale-Cedarbrae-Woburn,137,Woburn (137),-79.224706,43.757835
25,-79.210601,43.797415,26,GO-2004149400,2004/01/21 05:00:00+00,2004,January,Wednesday,21,21,...,Night,D42,0,0,146,Malvern East,132,Malvern (132),-79.210601,43.797415
26,-79.550561,43.725091,27,GO-2004250857,2004/04/13 04:00:00+00,2004,April,Tuesday,104,13,...,Evening,D23,1,0,5,Elms-Old Rexdale,5,Elms-Old Rexdale (5),-79.550561,43.725091
28,-79.579284,43.735235,29,GO-2004350484,2004/05/01 04:00:00+00,2004,May,Saturday,122,1,...,Evening,D23,1,0,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.579284,43.735235
29,-79.507743,43.717372,30,GO-2004518544,2004/06/12 04:00:00+00,2004,June,Saturday,164,12,...,Night,D31,0,0,28,Rustic,28,Rustic (28),-79.507743,43.717372
30,-79.311658,43.795977,31,GO-2004773793,2004/12/15 05:00:00+00,2004,December,Wednesday,350,15,...,Evening,D42,0,1,148,East L'Amoreaux,117,L'Amoreaux (117),-79.311658,43.795977
31,-79.233887,43.781741,32,GO-2004125755,2004/01/08 05:00:00+00,2004,January,Thursday,8,8,...,Morning,D42,1,0,142,Woburn North,137,Woburn (137),-79.233887,43.781741
32,-79.514764,43.767205,33,GO-2004315641,2004/04/17 04:00:00+00,2004,April,Saturday,108,17,...,Morning,D31,0,0,24,Black Creek,24,Black Creek (24),-79.514764,43.767205
33,-79.329337,43.697376,34,GO-2004301868,2004/05/02 04:00:00+00,2004,May,Sunday,123,2,...,Night,D54,1,0,58,Old East York,58,Old East York (58),-79.329337,43.697376
34,-79.383026,43.646599,35,GO-2004637474,2004/08/25 04:00:00+00,2004,August,Wednesday,238,25,...,Morning,D52,0,0,170,Yonge-Bay Corridor,76,Bay Street Corridor (76),-79.383026,43.646599
35,-79.367200,43.655009,36,GO-2004482932,2004/05/27 04:00:00+00,2004,May,Thursday,148,27,...,Night,D51,0,1,73,Moss Park,73,Moss Park (73),-79.367200,43.655009
36,-79.256513,43.730741,37,GO-2004232446,2004/03/13 05:00:00+00,2004,March,Saturday,73,13,...,Night,D41,0,0,124,Kennedy Park,124,Kennedy Park (124),-79.256513,43.730741
37,-79.302434,43.797213,38,GO-2004153036,2004/01/24 05:00:00+00,2004,January,Saturday,24,24,...,Evening,D42,0,0,148,East L'Amoreaux,117,L'Amoreaux (117),-79.302434,43.797213
38,-79.302434,43.797213,39,GO-2004497549,2004/09/30 04:00:00+00,2004,September,Thursday,274,30,...,Evening,D42,0,1,148,East L'Amoreaux,117,L'Amoreaux (117),-79.302434,43.797213
39,-79.263969,43.713990,40,GO-2004556110,2004/07/30 04:00:00+00,2004,July,Friday,212,30,...,Evening,D31,0,0,120,Clairlea-Birchmount,120,Clairlea-Birchmount (120),-79.263969,43.713990
40,-79.582142,43.689029,41,GO-2004414391,2004/05/24 04:00:00+00,2004,May,Monday,145,24,...,Evening,D23,0,0,1,West Humber-Clairville,1,West Humber-Clairville (1),-79.582142,43.689029
41,-79.366859,43.651086,42,GO-2004594159,2004/07/24 04:00:00+00,2004,July,Saturday,206,24,...,Night,D51,1,0,73,Moss Park,73,Moss Park (73),-79.366859,43.651086
42,-79.328071,43.667525,43,GO-2004668846,2004/09/24 04:00:00+00,2004,September,Friday,268,24,...,Night,D55,0,1,70,South Riverdale,70,South Riverdale (70),-79.328071,43.667525
43,-79.474292,43.755528,44,GO-2004239848,2004/04/21 04:00:00+00,2004,April,Wednesday,112,21,...,Night,D32,0,1,27,York University Heights,27,York University Heights (27),-79.474292,43.755528
44,-79.393274,43.648387,45,GO-2004295496,2004/04/16 04:00:00+00,2004,April,Friday,107,16,...,Night,D52,0,1,164,Wellington Place,77,Waterfront Communities-The Island (77),-79.393274,43.648387
45,-79.207795,43.808045,46,GO-2004136310,2004/01/06 05:00:00+00,2004,January,Tuesday,6,6,...,Evening,D42,0,0,146,Malvern East,132,Malvern (132),-79.207795,43.808045
46,-79.434983,43.649529,47,GO-2004314373,2004/04/17 04:00:00+00,2004,April,Saturday,108,17,...,Night,D14,0,1,84,Little Portugal,84,Little Portugal (84),-79.434983,43.649529
47,-79.589229,43.741088,48,GO-2004641371,2004/09/06 04:00:00+00,2004,September,Monday,250,6,...,Night,D23,0,0,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.589229,43.741088
48,-79.399312,43.656096,49,GO-2004135509,2004/01/04 05:00:00+00,2004,January,Sunday,4,4,...,Night,D14,0,2,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.399312,43.656096
49,-79.594207,43.741919,50,GO-2004421259,2004/05/28 04:00:00+00,2004,May,Friday,149,28,...,Evening,D23,0,0,2,Mount Olive-Silverstone-Jamestown,2,Mount Olive-Silverstone-Jamestown (2),-79.594207,43.741919
50,-79.302256,43.715983,51,GO-2004637869,2004/08/29 04:00:00+00,2004,August,Sunday,242,29,...,Night,D54,0,0,43,Victoria Village,43,Victoria Village (43),-79.302256,43.715983
51,-79.393856,43.653817,52,GO-2004303360,2004/04/11 04:00:00+00,2004,April,Sunday,102,11,...,Night,D52,0,1,78,Kensington-Chinatown,78,Kensington-Chinatown (78),-79.393856,43.653817
52,-79.614271,43.732183,53,GO-2004650681,2004/09/21 04:00:00+00,2004,September,Tuesday,265,21,...,Night,D23,1,0,1,West Humber-Clairville,1,West Humber-Clairville (1),-79.614271,43.732183

In [8]:
df2.describe()

,X,Y,OBJECTID,OCC_YEAR,OCC_DOY,OCC_DAY,OCC_HOUR,DEATH,INJURIES,LONG_WGS84,LAT_WGS84
count,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000,5643.000000
mean,-79.415076,43.719079,2874.332624,2014.532164,187.136807,15.905369,12.079745,0.122984,0.486443,-79.415076,43.719079
std,0.116379,0.048917,1643.956540,5.448039,100.372513,8.824548,8.685902,0.350381,0.781489,0.116379,0.048917
min,-79.625565,43.587343,1.000000,2004.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-79.625565,43.587343
25%,-79.512482,43.678879,1453.500000,2010.000000,106.000000,8.000000,3.000000,0.000000,0.000000,-79.512482,43.678879
50%,-79.438373,43.721312,2886.000000,2016.000000,192.000000,16.000000,15.000000,0.000000,0.000000,-79.438373,43.721312
75%,-79.327105,43.755510,4296.500000,2019.000000,268.000000,23.000000,20.000000,0.000000,1.000000,-79.327105,43.755510
max,-79.122053,43.838273,5707.000000,2022.000000,366.000000,31.000000,23.000000,3.000000,24.000000,-79.122053,43.838273

In [13]:
count_a = df2['NEIGHBOURHOOD_158'].str.count('Glenfield-Jane Heights').sum()
count_b = df2['NEIGHBOURHOOD_158'].str.count('Black Creek').sum()
count_c = df2['NEIGHBOURHOOD_158'].str.count('York University Heights').sum()

In [10]:
count_a

311

In [14]:
count_b

203

In [15]:
count_c

117

In [16]:
target_locations = ["Black Creek", "Glenfield-Jane Heights", "York University Heights"]
filtered_df = df2[df2["NEIGHBOURHOOD_158"].isin(target_locations)]
df2= filtered_df

In [17]:
df2

,X,Y,OBJECTID,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,...,OCC_TIME_RANGE,DIVISION,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
2,-79.518759,43.769157,3,GO-2004311851,2004/05/14 04:00:00+00,2004,May,Friday,135,14,...,Afternoon,D31,1,1,24,Black Creek,24,Black Creek (24),-79.518759,43.769157
32,-79.514764,43.767205,33,GO-2004315641,2004/04/17 04:00:00+00,2004,April,Saturday,108,17,...,Morning,D31,0,0,24,Black Creek,24,Black Creek (24),-79.514764,43.767205
43,-79.474292,43.755528,44,GO-2004239848,2004/04/21 04:00:00+00,2004,April,Wednesday,112,21,...,Night,D32,0,1,27,York University Heights,27,York University Heights (27),-79.474292,43.755528
72,-79.508172,43.743052,73,GO-2004602734,2004/07/13 04:00:00+00,2004,July,Tuesday,195,13,...,Afternoon,D31,0,1,25,Glenfield-Jane Heights,25,Glenfield-Jane Heights (25),-79.508172,43.743052
73,-79.522845,43.772989,74,GO-2004564223,2004/07/01 04:00:00+00,2004,July,Thursday,183,1,...,Night,D31,1,0,24,Black Creek,24,Black Creek (24),-79.522845,43.772989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,-79.519235,43.752866,5655,GO-20221946068,2022/10/06 04:00:00+00,2022,October,Thursday,279,6,...,Afternoon,D31,1,0,25,Glenfield-Jane Heights,25,Glenfield-Jane Heights (25),-79.519235,43.752866
5669,-79.489545,43.746807,5670,GO-20221757893,2022/09/10 04:00:00+00,2022,September,Saturday,253,10,...,Night,D31,1,0,27,York University Heights,27,York University Heights (27),-79.489545,43.746807
5673,-79.519288,43.770266,5674,GO-20222060043,2022/10/23 04:00:00+00,2022,October,Sunday,296,23,...,Night,D31,0,1,24,Black Creek,24,Black Creek (24),-79.519288,43.770266
5682,-79.509120,43.758127,5683,GO-2022514139,2022/03/19 04:00:00+00,2022,March,Saturday,78,19,...,Afternoon,D31,0,0,25,Glenfield-Jane Heights,25,Glenfield-Jane Heights (25),-79.509120,43.758127
5689,-79.494905,43.752169,5690,GO-2022183740,2022/01/26 05:00:00+00,2022,January,Wednesday,26,26,...,Night,D31,0,0,27,York University Heights,27,York University Heights (27),-79.494905,43.752169

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 631 entries, 2 to 5689
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   X                  631 non-null    float64
 1   Y                  631 non-null    float64
 2   OBJECTID           631 non-null    int64
 3   EVENT_UNIQUE_ID    631 non-null    object
 4   OCC_DATE           631 non-null    object
 5   OCC_YEAR           631 non-null    int64
 6   OCC_MONTH          631 non-null    object
 7   OCC_DOW            631 non-null    object
 8   OCC_DOY            631 non-null    int64
 9   OCC_DAY            631 non-null    int64
 10  OCC_HOUR           631 non-null    int64
 11  OCC_TIME_RANGE     631 non-null    object
 12  DIVISION           631 non-null    object
 13  DEATH              631 non-null    int64
 14  INJURIES           631 non-null    int64
 15  HOOD_158           631 non-null    object
 16  NEIGHBOURHOOD_158  631 non-null    object
 17  HOOD_140           631 non-null    object
 18  NEIGHBOURHOOD_140  631 non-null    object
 19  LONG_WGS84         631 non-null    float64
 20  LAT_WGS84          631 non-null    float64
dtypes: float64(4), int64(7), object(10)
memory usage: 108.5+ KB